spring:
  datasource:
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:test}?currentSchema=public
    username: ${DATABASE_USER:test}
    password: ${DATABASE_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          time_zone: UTC
          batch_size: 5
        order_updates: true
        order_inserts: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml

  main:
    allow-bean-definition-overriding: true